# -*- coding: utf-8 -*-
from FreeCAD import Base
Vec = Base.Vector

import numpy as np
import math

design_params = App.ActiveDocument.getObjectsByLabel('design_params')[0]
upcycled_fork = App.ActiveDocument.getObjectsByLabel('upcycled_fork')[0]
ref = App.ActiveDocument.getObjectsByLabel('References')[0]

aliases = {}
row = 1
row_empty = False
while not row_empty:
    name = None
    try:
        name = ref.get('A{}'.format(row))
    except ValueError:
        row_empty = True
    else:
        if name:
            aliases[name] = '{}'.format(row)
        else:
            row_empty = True
    row += 1

def setref(alias, value, units='mm'):
    ref.set(
        'B{}'.format(aliases[alias]),
        '{:.2f} {}'.format(value, units)
    )
    ref.set('C{}'.format(aliases[alias]), 'FROM PYTHON')

def copy_vector(vec):
    """
    Vectors cannot be copied using the python copy module,
    and don't otherwise have a built-in copy mechanism!  So
    this function should suffice.
    """
    return Vec(vec.x, vec.y, vec.z)

def rotation_matrix(axis, theta):
    """
    Return the rotation matrix associated with counterclockwise rotation about
    the given axis by theta radians.
    """
    axis = np.asarray(axis)
    axis = axis/math.sqrt(np.dot(axis, axis))
    a = math.cos(theta/2.0)
    b, c, d = -axis*math.sin(theta/2.0)
    aa, bb, cc, dd = a*a, b*b, c*c, d*d
    bc, ad, ac, ab, bd, cd = b*c, a*d, a*c, a*b, b*d, c*d
    return np.array([[aa+bb-cc-dd, 2*(bc+ad), 2*(bd-ac)],
                     [2*(bc-ad), aa+cc-bb-dd, 2*(cd+ab)],
                     [2*(bd+ac), 2*(cd-ab), aa+dd-bb-cc]])

def rotated_about_axis(vector, axis, theta):
    """
    Rotate the given Vector according to the given axis and theta.

    Returns:
        a new vector
    """
    rotated = np.dot(rotation_matrix(axis, theta), np.asarray(vector))
    return Vec(rotated)


class Cope(object):
    def reference_vector(self):
        raise(NotImplementedError)

    def angle(self):
        raise(NotImplementedError)

    def reference(self, first_cope):
        first_cope.get_centerline_facing_away()
        self.reference_vector()

        small_angle = first_cope.reference_vector().getAngle(self.reference_vector())
        if first_cope.get_centerline_facing_away().dot(first_cope.reference_vector().cross(self.reference_vector())) > 0:
            return small_angle
        else:
            return 0 - small_angle
        

class FlatCope(Cope):
    def __init__(self, centerline, tube_diameter, cut_face_normal):
        """
        Parameters:
            centerline (Vec): normalized vector representing the centerline
                of the tubing.
            cut_face_normal (Vec): normal vector of the cut face.
        """
        self.centerline = centerline
        self.cut_face_normal = cut_face_normal
        self.tube_diameter = tube_diameter

    def get_centerline_facing_away(self):
        if self.centerline.getAngle(self.cut_face_normal) > (math.pi/2):
            return self.centerline.negative()
        else:
            return self.centerline

    def reference_vector(self):
        centerline_facing_away = self.get_centerline_facing_away()
        return centerline_facing_away.cross(self.cut_face_normal)

    def angle(self):
        """
        Get a cut angle which would be indicated on a horizontal metal bandsaw.
        """
        return self.centerline.getAngle(self.cut_face_normal)


class CylindricalCope(Cope):
    def __init__(self, centerline, tube_diameter, cope_diameter, saw_direction):
        """
        Parameters:
            centerline (Vec): normalized vector representing the centerline
                of the tubing.
            saw_direction (Vec): axis of saw rotation, pointing in direction
                of cutting motion.
        """
        self.centerline = centerline
        self.saw_direction = saw_direction
        self.tube_diameter = tube_diameter
        self.cope_diameter = cope_diameter

    def get_centerline_facing_away(self):
        if self.centerline.getAngle(self.saw_direction.negative()) > (math.pi/2):
            return self.centerline.negative()
        else:
            return self.centerline

    def reference_vector(self):
        centerline_facing_away = self.get_centerline_facing_away()
        return centerline_facing_away.cross(self.saw_direction.negative()).cross(self.centerline)

    def angle(self):
        """
        Get a cut angle which would be indicated on a tubing notcher jig.
        """
        return self.saw_direction.getAngle(self.centerline) - (3.1415927/2)


class CopedTubing(object):
    def __init__(self, name, copes):
        self.name = name
        self.copes = copes

    def set_references(self):
        cope_idx = 0
        for cope in self.copes:
            cope_name = '{}/cope_{}'.format(self.name, cope_idx)
            setref('{}/angle'.format(cope_name), cope.angle(), 'rad')
            setref('{}/reference'.format(cope_name), cope.reference(self.copes[0]), 'rad')
            cope_idx += 1
            

# Calculating the copes for the cargo_front_tube_r
cargo_front_tube_r_centerline = App.ActiveDocument.getObjectsByLabel('cargo_front_tube_centerline')[0].Shape.tangentAt(1)

CopedTubing('cargo_front_tube_r', [
    # front tube / side tube joint
    CylindricalCope(
        cargo_front_tube_r_centerline.negative(),
        design_params.get('cargo_tube_diam'),
        design_params.get('cargo_tube_diam'),
        Vec(1, 0, 0), # represents centerline of cargo_side_tube
    ),
    # joint between two front tubes
    FlatCope(
        cargo_front_tube_r_centerline,
        design_params.get('cargo_tube_diam'),
        Vec(0, 1, 0), # represents normal face of cope
    ),
    # slot for front head tube
    CylindricalCope(
        cargo_front_tube_r_centerline,
        design_params.get('cargo_tube_diam'),
        upcycled_fork.get('front_head_tube_OD'),
        App.ActiveDocument.getObjectsByLabel('front_head_tube_cope_centerline')[0].Shape.tangentAt(1).negative(),
    ),
]).set_references()

# Calculating the copes for the lower_down_tube
lower_down_tube_centerline = Vec(1, 0, 0)

CopedTubing('lower_down_tube', [
    CylindricalCope(
        lower_down_tube_centerline,
        design_params.get('cargo_tube_diam'),
        design_params.get('cargo_tube_diam'),
        Vec(0, 1, 0),
    ),
    CylindricalCope(
        lower_down_tube_centerline,
        design_params.get('cargo_tube_diam'),
        design_params.get('rear_head_tube_od'),
        Vec(0, 0, 1),
    ),
]).set_references()


ref.recompute()

# vim: ft=python
